# Generated by Django 6.0.3 on 2026-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rank',
            field=models.PositiveIntegerField(verbose_name='rank'),
        ),
    ]
