# Generated by Django 6.0.3 on 2026-03-12 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone_number')),
                ('apartment', models.CharField(max_length=200, verbose_name='Apartment')),
                ('street', models.TextField(verbose_name='Street')),
                ('pincode', models.CharField(max_length=50, verbose_name='Pincode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
            },
        ),
        migrations.CreateModel(
            name='VerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='OTP Code')),
                ('type', models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset Password')], max_length=30, verbose_name='OTP Type')),
                ('expires_in', models.DateTimeField(verbose_name='Expiration In')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification OTP',
                'verbose_name_plural': 'Verification OTPs',
            },
        ),
    ]
