# Generated by Django 6.0.3 on 2026-03-24 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraddress_verificationotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='\\+\\((?:998\\))([0-9]{2})([0-9]{3})(\\d{2})(\\d{2})')], verbose_name='Phone_number'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d{6}$')], verbose_name='Pincode'),
        ),
    ]
