# Generated by Django 6.0.3 on 2026-03-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('code', models.CharField(max_length=2, verbose_name='code')),
            ],
        ),
        migrations.RemoveField(
            model_name='region',
            name='code',
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='region',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='common.country'),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
