# Generated by Django 6.0.3 on 2026-03-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_country_remove_region_code_alter_region_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='country',
        ),
    ]
