# Generated by Django 6.0.3 on 2026-03-24 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_region_region_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='media/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'heif', 'png', 'pdf', 'mp3', 'mp4', 'docx', 'wav', 'mov'])], verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('music', 'Music')], max_length=30, verbose_name='type'),
        ),
    ]
